### ISSUE TITLE
Feature: Managing the speed of lyrics

### ISSUE THREAD

**Issue by VinayChaurasiyaA** [boidushya/better-lyrics-api#4]
Whenever a user clicks on the "forward or backward button" to make sure his lyrics are at right time.

**Comment by VinayChaurasiyaA** [comment]
Here is a piece of code, can you like have a glimpse on it,

  `

    func shiftLyrics(w http.ResponseWriter, r *http.Request) {
        direction := r.URL.Query().Get("direction")
        trackID := // retrieve the current trackID
        cacheKey := fmt.Sprintf("lyrics:%s", trackID)
        cachedLyrics, ok := getCache(cacheKey)
        if !ok {
            http.Error(w, "Lyrics not found in cache", http.StatusNotFound)
            return
        }

    lyrics := []Line{}
    json.Unmarshal([]byte(cachedLyrics), &lyrics)

    shiftDuration := time.Second // Adjust the duration as needed
    for i := range lyrics {
        if direction == "forward" {
            lyrics[i].StartTime = lyrics[i].StartTime.Add(shiftDuration)
        } else if direction == "backward" {
            lyrics[i].StartTime = lyrics[i].StartTime.Add(-shiftDuration)
        }
    }

    updatedLyrics, _ := json.Marshal(lyrics)
    setCache(cacheKey, string(updatedLyrics), time.Duration(conf.Configuration.LyricsCacheTTLInSeconds)*time.Second)

    w.Header().Set("Content-Type", "application/json")
    json.NewEncoder(w).Encode(map[string]interface{}{
        "error":   nil,
        "trackId": trackID,
        "lyrics":  lyrics,
    })
    }

`

**Comment by boidushya** [comment]
I understand this is pseudocode, but this will not work with Better Lyrics since the shift needs to happen locally and not globally as you've implemented in the backend. 
By opening an issue for a feature request i meant to open it [over here](https://github.com/boidushya/better-lyrics/issues/new/choose)
